# Generated by Django 3.0.1 on 2020-02-07 16:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_idea', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 22, 30, 45, 145575))),
                ('category', models.ManyToManyField(to='ideapeacher.category')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('message_time', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 22, 30, 45, 148607))),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 22, 30, 45, 147613))),
                ('by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('on_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ideapeacher.idea')),
            ],
        ),
        migrations.CreateModel(
            name='ideapeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='peacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ideapeacher.ideapeacher'),
        ),
    ]
