# Generated by Django 3.0.1 on 2020-02-09 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideapeacher', '0003_auto_20200209_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 17, 51, 21, 217162)),
        ),
        migrations.AlterField(
            model_name='idea',
            name='pdf',
            field=models.FileField(blank=True, upload_to='book/pdfs'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 17, 51, 21, 219160)),
        ),
        migrations.AlterField(
            model_name='public',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 17, 51, 21, 218160)),
        ),
    ]
