# Generated by Django 3.0.1 on 2020-02-09 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideapeacher', '0004_auto_20200209_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='idea',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 18, 0, 31, 476584)),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 18, 0, 31, 477581)),
        ),
        migrations.AlterField(
            model_name='public',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 18, 0, 31, 477581)),
        ),
    ]
