# Generated by Django 3.0.1 on 2020-02-09 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideapeacher', '0005_auto_20200209_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='pdf',
            field=models.FileField(blank=True, upload_to='idea'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 23, 31, 6, 433920)),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 23, 31, 6, 434917)),
        ),
        migrations.AlterField(
            model_name='public',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 23, 31, 6, 434917)),
        ),
    ]
