# Generated by Django 3.0.2 on 2020-02-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200205_0943'),
        ('main', '0004_auto_20200205_0102'),
    ]

    operations = [
    ]
