# Generated by Django 3.0.1 on 2020-02-05 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20200205_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public',
            old_name='public_comment',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='idea',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 23, 13, 29, 568254)),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 23, 13, 29, 573636)),
        ),
        migrations.AlterField(
            model_name='public',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 23, 13, 29, 572248)),
        ),
    ]
