# Generated by Django 3.0.1 on 2020-02-05 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200205_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 6, 0, 3, 12, 456629)),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 6, 0, 3, 12, 462313)),
        ),
        migrations.AlterField(
            model_name='public',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 6, 0, 3, 12, 459709)),
        ),
        migrations.RemoveField(
            model_name='public',
            name='post',
        ),
        migrations.AddField(
            model_name='public',
            name='post',
            field=models.ManyToManyField(to='main.idea'),
        ),
    ]
