# Generated by Django 3.0.1 on 2020-02-05 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200206_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public',
            old_name='post',
            new_name='on_post',
        ),
        migrations.AlterField(
            model_name='idea',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 6, 0, 10, 41, 311735)),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 6, 0, 10, 41, 320752)),
        ),
        migrations.AlterField(
            model_name='public',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 6, 0, 10, 41, 318767)),
        ),
    ]
